version: "0.0.{build}"
branches:
  only:
    - master
skip_commits:
  files:
    - "*.md"
image:
  - Ubuntu
configuration:
  - Release
artifacts:
  - path: publish/*.nupkg
platform: Any CPU
before_build:
  - dotnet tool restore
  - dotnet restore -v Minimal
build_script:
  - dotnet build
  - dotnet pack --no-build -o publish -p:PackageVersion=$APPVEYOR_BUILD_VERSION
test_script:
  - dotnet test src/Quibble.Xunit.Tests
deploy:
  - provider: Environment
    name: Nuget v2