//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidJson {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StupidJson.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor should be stupid as JSON.
        /// </summary>
        internal static string CtorAnalyzerDescription {
            get {
                return ResourceManager.GetString("CtorAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} has a non-default constructor that makes JSON deserialization harder than it needs to be..
        /// </summary>
        internal static string CtorAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CtorAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stupid JSON constructor.
        /// </summary>
        internal static string CtorAnalyzerTitle {
            get {
                return ResourceManager.GetString("CtorAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string DebugAnalyzerDescription {
            get {
                return ResourceManager.GetString("DebugAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug message: {0}.
        /// </summary>
        internal static string DebugAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("DebugAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string DebugAnalyzerTitle {
            get {
                return ResourceManager.GetString("DebugAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialization target type should be stupid as JSON.
        /// </summary>
        internal static string DeserializeAnalyzerDescription {
            get {
                return ResourceManager.GetString("DeserializeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is target for JSON deserialization but contains elements that make deserialization harder than it needs to be..
        /// </summary>
        internal static string DeserializeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("DeserializeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stupid JSON deserialization.
        /// </summary>
        internal static string DeserializeAnalyzerTitle {
            get {
                return ResourceManager.GetString("DeserializeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property types should be stupid as JSON.
        /// </summary>
        internal static string PropAnalyzerDescription {
            get {
                return ResourceManager.GetString("PropAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of {0} is not JSON friendly. {1}.
        /// </summary>
        internal static string PropAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("PropAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stupid JSON property type.
        /// </summary>
        internal static string PropAnalyzerTitle {
            get {
                return ResourceManager.GetString("PropAnalyzerTitle", resourceCulture);
            }
        }
    }
}
